### ISSUE TITLE
 This extension is not listed in the Chrome Web Store and may have been added without your knowledge

### ISSUE THREAD

**Issue by MeshkaniMohammad** [manojVivek/medium-unlimited#10]
I can't enable medium-unlimited extension!
I got this error:
 "This extension is not listed in the Chrome Web Store and may have been added without your knowledge"

**Comment by srkn** [comment]
This extension does not work anymore

**Comment by manojVivek** [comment]
@MeshkaniMohammad @srkn The extension was unlisted from the Google Chrome store as it was violating the store policy. 

You can follow this thread on how to get it working again - #8 

Please let me know if you have any other questions.

**Comment by ngiakhanh** [comment]
I can't enable it too.

**Comment by cdswyda** [comment]
I already install it, but it has been disabled by Chrome, and I can't enabled it.
