### ISSUE TITLE
Extension not working for betterprogramming.pub

### ISSUE THREAD

**Issue by alijay110** [manojVivek/medium-unlimited#102]
Hi,

I have just come across this upgrade dialog box after ages.
I believe this extension is not working for this domain: _betterprogramming.pub_

Would be much appreciated, If it can be looked at.

Many thanks

**Comment by manojVivek** [comment]
@alijay110  I just made a fix for this on the latest version(v1.6.0), please update the extension and let me know if you still face the problem.

Link to update: https://manojvivek.github.io/medium-unlimited/download/
