### ISSUE TITLE
Extension Not Working - Unable To Open Premium Articles (From 24/2/21)

### ISSUE THREAD

**Issue by dczeus** [manojVivek/medium-unlimited#103]
This extension was working like a charm. But from today it's not working at all. Unable to open any premium articles. Please fix it. Thanks :)

**Comment by LarsOlt** [comment]
Same problem here

**Comment by dczeus** [comment]
> Same problem here

Found any solution bro ??

**Comment by shuboy2014** [comment]
@manojVivek any update on this ?

**Comment by nayakayp** [comment]
Yes the extension stopped working. What happen to me is Medium keep lock the content over and over again after the extension open it. Maybe you need to update @manojVivek it?

**Comment by ssi-anik** [comment]
Seems like he stopped working on this project. lots of PRs are in the pending state and don't get cleared.

**Comment by rablinz** [comment]
I found that the Medium Hackd extension for chrome works very well, regardless of which medium domain is being used.

**Comment by ssi-anik** [comment]
> I found that the Medium Hackd extension for chrome works very well, regardless of which medium domain is being used.

I didn't check their codebase. Did you go through their codebase? I am rather following my fork of this repo. whenever required, I add them to my repo and keep my repo updated.

**Comment by HereticSK** [comment]
@ssi-anik Thank u for your sharing! I tried to build from the repo you forked, and got a version 1.5.0. But that version didn't work, either. Is there anything I was missing? Or how can I provide more information to help you check? Thanks.

**Comment by ssi-anik** [comment]
@HereticSK no, you're doing things right. You can just press the "clear all" or the "recycle bin" button. It's causing cause the extension tries to send some usage data to some third-party service and the API token is not given. That's why it's returning the 4xx status code. It's all good.
As you could build the package, I guess you also know what's browser's inspect element's network tab. If you check the network tab and a medium article, you'll find the 'refer' header being sent to the server.
Check and if there is anything wrong, mention here.

**Comment by HereticSK** [comment]
@ssi-anik I opened an article https://towardsdatascience.com/why-neural-nets-can-approximate-any-function-a878768502f0

Found a 'refer' entry in the request headers in a file named after the url. Is this where I should look at? Then I got a twitter short link. https://t.co/agvyj8lu8kr   But twitter says the page doesn't exist. Same result for other articles.

![image](https://user-images.githubusercontent.com/17619612/110237125-03684b80-7f75-11eb-9591-80695a63557e.png)

**Comment by ssi-anik** [comment]
@HereticSK The `refer` headers value of twitter links are random. They don't exist. Yes, I have checked the towardsdatascience domain, and they don't work for some reason. But the listed other domains work fine.

**Comment by manojVivek** [comment]
@dczeus @LarsOlt @shuboy2014 @nayakayp @rablinz @HereticSK  I just made a fix for this on the latest version(v1.6.0), please update the extension and let me know if you still face the problem.

Link to update: https://manojvivek.github.io/medium-unlimited/download/

**Comment by ssi-anik** [comment]
You're so cool bro. :kissing_heart:  @manojVivek

**Comment by JaiRelan** [comment]
Hey @manojVivek,
Thanks a lot for this fix... I'm encountering a problem where the profile images and (sometimes other images too) are not loading... Could you please look into this?

Cheers,
J
