### ISSUE TITLE
No need to do all this stuff. Just chrome incognito window is enough

### ISSUE THREAD

**Issue by FazeelUsmani** [manojVivek/medium-unlimited#104]
Hi, @manojVivek and team. You can easily read medium articles using Google Chrome Incognito tab. Do try it once!

![image](https://user-images.githubusercontent.com/8823157/109039234-90e4a980-76f2-11eb-83b9-c4234e365f63.png)

**Comment by dczeus** [comment]
Of course, we can do that bro. But can we comment or clap on articles?
Plus this extension is the easiest way to operate on medium :)
Lemme know if you find any solution.Cheers :)

**Comment by FazeelUsmani** [comment]
Ooh! then it's good. I thought the main aim of this repo is just to read medium articles. 
Thanks! @dczeus
