### ISSUE TITLE
Addon firefox fails with especific post

### ISSUE THREAD

**Issue by kascesar** [manojVivek/medium-unlimited#106]
i found a post in towardsdatascience that can't go in with the addon
The post i mean is this:
https://towardsdatascience.com/clustering-metrics-better-than-the-elbow-method-6926e1f723a6

I post this only for curiosity, it may be study in the near future. Or just is a fail in my notebook only.

**Comment by ssi-anik** [comment]
Seems like it fails for everyone even tho it passes the `referer` header

![image](https://user-images.githubusercontent.com/2676602/109986961-69b05c80-7d30-11eb-83c0-4d822c5a21e4.png)

**Comment by manojVivek** [comment]
@kascesar @ssi-anik I just made a fix for this on the latest version(v1.6.0), please update the extension and let me know if you still face the problem.

Link to update: https://manojvivek.github.io/medium-unlimited/download/

**Comment by kascesar** [comment]
Thanks a lot nice Job very quickly! :D works!
