### ISSUE TITLE
the firefox extention for medium-unlimited does not seem to be working

### ISSUE THREAD

**Issue by chiranjeet14** [manojVivek/medium-unlimited#107]
https://addons.mozilla.org/en-US/firefox/addon/medium-unlimited-read-for-free/reviews/?score=1

**Comment by manojVivek** [comment]
@chiranjeet14  I just made a fix for this on the latest version(v1.6.0), please update the extension and let me know if you still face the problem.

Link to update: https://manojvivek.github.io/medium-unlimited/download/
