### ISSUE TITLE
Cannot unlock links

### ISSUE THREAD

**Issue by nguyenthanhquang152** [manojVivek/medium-unlimited#108]
I access this link but medium-unlimited cannot unlock it. (Tested with chrome extension)
https://medium.com/swlh/5-software-engineering-interview-questions-to-identify-outstanding-developers-6d8c95b46d64

**Comment by ssi-anik** [comment]
Working fine on my forked repo. You may use that.
![image](https://user-images.githubusercontent.com/2676602/110240682-4fb48b00-7f77-11eb-8ea2-4a22724f5c03.png)

**Comment by manojVivek** [comment]
@nguyenthanhquang152  I just made a fix for this on the latest version(v1.6.0), please update the extension and let me know if you still face the problem.

Link to update: https://manojvivek.github.io/medium-unlimited/download/
