### ISSUE TITLE
Extension unable to read articles.

### ISSUE THREAD

**Issue by EugeneGohh** [manojVivek/medium-unlimited#109]
It has been a few days, seems like this extension is not working anymore.

![Untitled](https://user-images.githubusercontent.com/64187129/110193710-85228100-7e70-11eb-9b30-d704b11e68c1.png)

**Comment by manojVivek** [comment]
@EugeneGohh  I just made a fix for this on the latest version(v1.6.0), please update the extension and let me know if you still face the problem.

Link to update: https://manojvivek.github.io/medium-unlimited/download/

**Comment by EugeneGohh** [comment]
> @EugeneGohh I just made a fix for this on the latest version(v1.6.0), please update the extension and let me know if you still face the problem.
> 
> Link to update: https://manojvivek.github.io/medium-unlimited/download/



> @EugeneGohh I just made a fix for this on the latest version(v1.6.0), please update the extension and let me know if you still face the problem.
> 
> Link to update: https://manojvivek.github.io/medium-unlimited/download/

Thank you so much, it works.
