### ISSUE TITLE
Not working on external publishers

### ISSUE THREAD

**Issue by mmphego** [manojVivek/medium-unlimited#11]
URL: https://medium.mybridge.co/36-amazing-python-open-source-projects-v-2019-2fe058d79450

![image](https://user-images.githubusercontent.com/7910856/56713708-cf922d00-6732-11e9-8a2a-37c8c5fa694b.png)

Current version:

![image](https://user-images.githubusercontent.com/7910856/56713785-08ca9d00-6733-11e9-87ce-83d5dd4476a0.png)

**Comment by manojVivek** [comment]
@mmphego I have added the custom domain, please update the addon from here - https://addons.mozilla.org/en-US/firefox/addon/medium-unlimited-read-for-free/

Thanks!
