### ISSUE TITLE
Medium-unlimited is dead. Long live medium-unlimited! (with link to working fork)

### ISSUE THREAD

**Issue by happyteque** [manojVivek/medium-unlimited#111]
Thanks for the extension @manojVivek, but it sadly appears to be dead (no signals from the main dev and there are pending PRs which are months old). Funnily enough, the last commit from @manojVivek was `funding.yml` ... I guess he was trying to send a message 😉 

I have had success using @ssi-anik's fork, which for all intents and purposes is now _the_ official version! Thanks @ssi-anik!
https://github.com/ssi-anik

**Comment by ssi-anik** [comment]
@taleslimaf here is the zip
[dist.zip](https://github.com/manojVivek/medium-unlimited/files/6110734/dist.zip)

But with much grief, I'd like to say some of the links are not working and don't have any idea why!
- https://medium.com/@jacksonz666/fill-the-gap-of-credential-management-in-github-actions-a313e230e58b
- https://hafiqiqmal93.medium.com/tips-to-speed-up-database-query-in-laravel-f194f624cb06
- any of the articles of this guy. https://medium.com/@jacksonz666

Again, the followings are working fine
- https://medium.com/swlh/gen-z-is-shaping-the-next-generation-of-the-internet-and-fast-4ea5cf570fc3
- https://medium.com/swlh/5-tips-to-make-better-decisions-lessons-from-ceos-behavioral-economists-a-pro-poker-player-1561d1d730f
- https://medium.com/swlh/how-to-fund-your-startup-if-it-isnt-a-rocketship-c27c8c0d8e9b

@happyteque

**Comment by toandaominh1997** [comment]
Hi @ssi-anik. Thank you for your fork repo. I have some error when downloading your zip dist.zip

`background.bundle.js:1 (anonymous function)
!function(t){var n={};function e(r){if(n[r])return n[r].exports;var i=n[r]={i:r,l:!1,exports:{}};return .............`
Any idea to fix it? Thanks

**Comment by ssi-anik** [comment]
@toandaominh1997 click the errors buttons, then clear all. that's all. it's okay otherwise.

**Comment by toandaominh1997** [comment]
@ssi-anik  Look like this extension that it can't unlock towardsdatascience.com. Some link that I can't access:

- https://towardsdatascience.com/lime-how-to-interpret-machine-learning-models-with-python-94b0e7e4432e
Any idea to fix it? Thanks

**Comment by ssi-anik** [comment]
any of the links from towards ds is not working plus some of the medium links I have randomly chosen (listed above) are not also working. no idea yet.

**Comment by toandaominh1997** [comment]
Anyway, it's a good job. Thank you for everything. Have a nice day to @ssi-anik

**Comment by ssi-anik** [comment]
Nah, it's working fine. Got the issue. Updating the readme.

![image](https://user-images.githubusercontent.com/2676602/110617145-8aa8ff80-81bf-11eb-8237-516fc80da3d9.png)

**Comment by ssi-anik** [comment]
I was thinking wrong. :angry: It's the same. medium is blocking those `referer` header I guess.

**Comment by ace3** [comment]
I think the t.co header is not working partially  since 1st march. I tried to open the medium link I posted on  Twitter, it not working too.

**Comment by ssi-anik** [comment]
Yes, I tried the same even by disabling the extension so that the extension doesn't remove and add new t.co link.

**Comment by ssi-anik** [comment]
BTW, if I'm alive, I'll try to upgrade the extension so that you can read from the main window. even if you can't make comment or clap that article.

**Comment by manojVivek** [comment]
@happyteque @taleslimaf @toandaominh1997 @mike123vn @ace3 @ssi-anik The latest version v1.6.0 has a fix for this issue, please update the extension and please let me know if you still face the problem.

Thanks for your patience!

**Comment by ssi-anik** [comment]
Thanks for the update finally. I have also completed the extension from my side. Long live Medium unlimited. <3

**Comment by Aarekaz** [comment]
@manojVivek It's not working for me, I removed the extension and reloaded the updated one, but it shows this and keeps refreshing.
![image](https://user-images.githubusercontent.com/36888347/111032279-7a00bf80-8433-11eb-986b-bb67ea5f564a.png)
