### ISSUE TITLE
Not working March 2021

### ISSUE THREAD

**Issue by Masum06** [manojVivek/medium-unlimited#112]
Medium pages glitch, and automatically keeps reloading. But does not unlock. Also this error showed up inside the extension details in chrome.

![image](https://user-images.githubusercontent.com/14367438/111027449-9cd2aa00-841a-11eb-9ce5-364faece3277.png)

**Comment by huymichael** [comment]
the same problem too

**Comment by Aarekaz** [comment]
Same problem here, even if I updated to the latest version 1.6

**Comment by kascesar** [comment]
Same problem u.u

**Comment by EugeneGohh** [comment]
Same problem here

**Comment by c4explosive** [comment]
Same problem, reloading infinity loop.

**Comment by EugeneGohh** [comment]
![Untitled](https://user-images.githubusercontent.com/64187129/111097835-3c0fb280-857d-11eb-8563-c911b23bbb82.png)

**Comment by yangrong688** [comment]
same problem in both firefox and chrome

**Comment by francidellungo** [comment]
Same problem in firefox

**Comment by karimelgazar** [comment]
the extension after unlocking the article it keeps on reloading the page and I can't stop it

**Comment by Jashandeep2020** [comment]
Anyone working on this error?

**Comment by Rahulsharma0810** [comment]
+1

**Comment by facundofacio** [comment]
+1

**Comment by Manonicu** [comment]
+1

**Comment by manojVivek** [comment]
Working on a fix, it should go live in a day or two.

**Comment by fawang** [comment]
Same issue on this page: https://towardsdatascience.com/bert-nlp-how-to-build-a-question-answering-bot-98b1d1594d7b

**Comment by cheuhyakuroku** [comment]
same issue. medium page always show loading content and refresh navigator😖

**Comment by und3fined** [comment]
always reload page :(

**Comment by manojVivek** [comment]
The fix for this has gone live with the latest version(v1.7.0). Please update the extension and let me know if you still face this issue.

**Comment by Manonicu** [comment]
> The fix for this has gone live with the latest version(v1.7.0). Please update the extension and let me know if you still face this issue.

nice work , absolutely fixed

**Comment by huymichael** [comment]
> The fix for this has gone live with the latest version(v1.7.0). Please update the extension and let me know if you still face this issue.
It works. Thanks mate

**Comment by facundofacio** [comment]
Thanks!!!

**Comment by itsfarseen** [comment]
I'm on version 1.7.0 on firefox. It's showing the same problem for me.
Medium gets loaded and the Medium unlocked sticky icon appears on the right. But within a second, medium reloads and shows the Sign in to read thing after the first paragraph.
