### ISSUE TITLE
Not working on subdomain.medium.com

### ISSUE THREAD

**Issue by impredicative** [manojVivek/medium-unlimited#12]
Non-working examples:
* https://onezero.medium.com/the-insane-demand-for-cybersecurity-workers-cb98abf964bc?source=rss-------8-----------------cybersecurity
* https://onezero.medium.com/the-tyranny-of-convenience-2e7fa145ab4

This should probably be an easy fix.

**Comment by aviwad** [comment]
I experience the same issue

**Comment by xameeramir** [comment]
Does not work for https://humanparts.medium.com/30-years-of-depression-gone-3dffafabc7cf

**Comment by manojVivek** [comment]
@impredicative @aviwad @xameeramir I have updated the plugin with the requested domains in the 1.4.3 version. 

Please update update your addons from below links, thanks!

Chrome: https://medium-unlimited.ml/download/
Firefox: https://addons.mozilla.org/en-US/firefox/addon/medium-unlimited-read-for-free/

**Comment by aviwad** [comment]
Thanks <3

**Comment by Insiderser** [comment]
Also, it doesn't work for https://elemental.medium.com/can-better-habits-and-therapy-replace-adhd-drugs-245750b27d87

**Comment by impredicative** [comment]
@manojVivek Is it possible to get it working for all of *.medium.com?

**Comment by manojVivek** [comment]
@impredicative @Insiderser I have now released a new version supporting *.medium.com. 

Please update here:
For chrome - https://medium-unlimited.ml/download/
For Firefox - https://addons.mozilla.org/en-US/firefox/addon/medium-unlimited-read-for-free/

**Comment by aviwad** [comment]
awesome

**Comment by xameeramir** [comment]
Great! Thanks a loads!
