### ISSUE TITLE
Package is Invalid Error "CRX_REQUIRED_PROOF_MISSING"

### ISSUE THREAD

**Issue by pavankjadda** [manojVivek/medium-unlimited#14]
When I try to install on Chrome I get an error message, as shown below
```
Package is Invalid Error "CRX_REQUIRED_PROOF_MISSING"
```
![Screen Shot 2019-06-18 at 3 49 52 PM](https://user-images.githubusercontent.com/17564080/59715009-eb6cf900-91e0-11e9-9747-eb45a8576065.png)

**Comment by ngiakhanh** [comment]
You cannot install this extension for Chrome. It is forbidden. If you want, you can only install it via Opera.

**Comment by pavankjadda** [comment]
Thanks. I was able to extract the `crx` file to zip file and use it as an unpacked extension.  Uploaded the code to my Github.

**Comment by manojVivek** [comment]
@pavankjadda @ngiakhanh I have fixed it now and it works for direct downloads from https://medium-unlimited.ml/download/.

Thank you!

**Comment by pavankjadda** [comment]
@manojVivek I cannot enable the extension in settings and I see the following error 

![Screen Shot 2019-06-27 at 4 41 59 PM](https://user-images.githubusercontent.com/17564080/60299418-a6d91000-98fa-11e9-8bb1-62437a01fa66.png)

**Comment by pavankjadda** [comment]
Never mind, this happens in Brave browser, not in Google chrome
