### ISSUE TITLE
Failure to unlock some stories

### ISSUE THREAD

**Issue by tsitsiflora** [manojVivek/medium-unlimited#15]
Hi, 
I'm not sure if this qualifies as an issue or not. I tried unlocking a story but instead, it redirects me to another page. Is this because it's a publication.

I tried for the Better Programming and Software Engineering publications

![issue](https://user-images.githubusercontent.com/27960081/60324628-95891580-9985-11e9-9812-fb6aabd2f252.png)

The picture shows the page that it is redirecting to.

**Comment by mrdaliri** [comment]
I can confirm it.

As a workaround, you can use browser back button to get back to the story page. It then shows the full story.

**Comment by manojVivek** [comment]
@tsitsiflora @mrdaliri Thanks for notifying me of this issue. I have identified the cause and fixed it in the version 1.4.5.

Please update your extension by visiting - https://medium-unlimited.ml/download/

Thank you!

**Comment by tsitsiflora** [comment]
Thanks!
*Tsitsi Flora Munikwa*
