### ISSUE TITLE
[BUG]: 1.9.0 doesn't work anymore

### ISSUE THREAD

**Issue by Drjacky** [manojVivek/medium-unlimited#150]
<img width="624" alt="Screen Shot 2021-05-22 at 16 47 47" src="https://user-images.githubusercontent.com/2296754/119232547-7ff2db00-bb1d-11eb-89f3-59dc64eb7480.png">

**Comment by EugeneGohh** [comment]
There is an up-to-date version. Please update it and try again.

**Comment by Plutonium-239** [comment]
What I have seen in my time using this is that it only unlocks 'locked' articles. That is, the 3 free stories count as unlocked since you can already view them. So the extension doesn't do anything.

**Comment by EugeneGohh** [comment]
> What I have seen in my time using this is that it only unlocks 'locked' articles. That is, the 3 free stories count as unlocked since you can already view them. So the extension doesn't do anything.

Have you checked the commit history? It has been updated.

**Comment by Drjacky** [comment]
@EugeneGohh 
@manojVivek 

Version: 1.10.0
<img width="747" alt="Screen Shot 2021-06-01 at 09 04 22" src="https://user-images.githubusercontent.com/2296754/120288652-5de51f80-c2b8-11eb-8635-a263717d2f75.png">

**Comment by Plutonium-239** [comment]
@Drjacky you need to finish your 3 free articles before the articles will start getting locked by medium. When that happens, medium unlimited will unlock your articles. 
The point is, the extension cannot unlock articles if they aren't locked to begin with.
