### ISSUE TITLE
[Bug] Uncaught (in promise) TypeError: Cannot read property 'remove' of null

### ISSUE THREAD

**Issue by tanlin2013** [manojVivek/medium-unlimited#152]
* Error message:  
Uncaught (in promise) TypeError: Cannot read property 'remove' of null
* Occurred on URL: 
https://towardsdatascience.com/5-exciting-deep-learning-advancements-to-keep-your-eye-on-in-2021-6f6a9b6d2406
* Description:
<img width="674" alt="Screen Shot 2021-05-27 at 1 55 11 PM" src="https://user-images.githubusercontent.com/24889824/119773884-e304b900-bef3-11eb-8280-e34001e6b955.png">

Thanks again for your hard working on this wonderful project!  🚀🚀🚀

**Comment by EugeneGohh** [comment]
> * Error message:
>   Uncaught (in promise) TypeError: Cannot read property 'remove' of null
> * Occurred on URL:
>   https://towardsdatascience.com/5-exciting-deep-learning-advancements-to-keep-your-eye-on-in-2021-6f6a9b6d2406
> * Description:
> 
> <img alt="Screen Shot 2021-05-27 at 1 55 11 PM" width="674" src="https://user-images.githubusercontent.com/24889824/119773884-e304b900-bef3-11eb-8280-e34001e6b955.png">
> 
> Thanks again for your hard working on this wonderful project! 🚀🚀🚀

Have you updated to the current version?

**Comment by tanlin2013** [comment]
Right... Thanks for pointing out. I'm indeed a bit behind (ver. 1.7.0). Updating to ver. 1.10.0 has solved the problem.
