### ISSUE TITLE
did npm run dev - got this back from cmd in administrator mode 

### ISSUE THREAD

**Issue by emailsubjekt** [manojVivek/medium-unlimited#16]
I set cmd to the location of 
D:\PROGRAMI\Github\medium-unlimited-master
and then wrote your instructions 'npm run dev' and I got this out, what? How do I make a chrome extension that I can drag into crhome and install? 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle medium-unlimited@1.0.0~predev: medium-unlimited@1.0.0
6 info lifecycle medium-unlimited@1.0.0~dev: medium-unlimited@1.0.0
7 verbose lifecycle medium-unlimited@1.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle medium-unlimited@1.0.0~dev: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\PROGRAMI\Github\medium-unlimited-master\node_modules\.bin;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\MSC.Software\Adams\2018\bin;C:\Users\siris\AppData\Local\Microsoft\WindowsApps;C:\Users\siris\AppData\Local\Programs\Microsoft VS Code\bin;C:\flutter\bin;C:\Users\siris\AppData\Roaming\npm
9 verbose lifecycle medium-unlimited@1.0.0~dev: CWD: D:\PROGRAMI\Github\medium-unlimited-master
10 silly lifecycle medium-unlimited@1.0.0~dev: Args: [ '/d /s /c', 'webpack --mode development  --watch' ]
11 silly lifecycle medium-unlimited@1.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle medium-unlimited@1.0.0~dev: Failed to exec dev script
13 verbose stack Error: medium-unlimited@1.0.0 dev: `webpack --mode development  --watch`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid medium-unlimited@1.0.0
15 verbose cwd D:\PROGRAMI\Github\medium-unlimited-master
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error medium-unlimited@1.0.0 dev: `webpack --mode development  --watch`
22 error Exit status 1
23 error Failed at the medium-unlimited@1.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by emailsubjekt** [comment]
I did npm run build too

D:\PROGRAMI\Github\medium-unlimited-master>npm run build

> medium-unlimited@1.0.0 build D:\PROGRAMI\Github\medium-unlimited-master
> webpack --mode production

'webpack' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! medium-unlimited@1.0.0 build: `webpack --mode production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the medium-unlimited@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\siris\AppData\Roaming\npm-cache\_logs\2019-06-30T01_07_41_572Z-debug.log

D:\PROGRAMI\Github\medium-unlimited-master>

**Comment by srivatsav1998** [comment]
Try running `npm install` before `npm run dev/ build`

**Comment by emailsubjekt** [comment]
after npm install, did npm run dev, got this and then cmd froze and I couldn't type anything else in


> medium-unlimited@1.0.0 dev D:\PROGRAMI\Github\medium-unlimited-master
> webpack --mode development  --watch

i ｢webpack｣: Watching enabled
[copy-webpack-plugin] processing from: 'static' to: 'static'
[copy-webpack-plugin] processing from: 'src/html' to: 'html'
[copy-webpack-plugin] processing from: 'manifest.json' to: 'manifest.json'
[copy-webpack-plugin] begin globbing 'D:\PROGRAMI\Github\medium-unlimited-master\static/**/*' with a context of 'D:\PROGRAMI\Github\medium-unlimited-master\static'
[copy-webpack-plugin] WARNING - unable to locate 'src/html' at 'D:\PROGRAMI\Github\medium-unlimited-master\src\html'
[copy-webpack-plugin] begin globbing 'D:\PROGRAMI\Github\medium-unlimited-master\manifest.json' with a context of 'D:\PROGRAMI\Github\medium-unlimited-master'
[copy-webpack-plugin] determined that 'D:/PROGRAMI/Github/medium-unlimited-master/manifest.json' should write to 'manifest.json'
[copy-webpack-plugin] reading D:\PROGRAMI\Github\medium-unlimited-master\manifest.json to write to assets
[copy-webpack-plugin] determined that 'D:/PROGRAMI/Github/medium-unlimited-master/static/floating_button_256.png' should write to 'static/floating_button_256.png'
[copy-webpack-plugin] determined that 'D:/PROGRAMI/Github/medium-unlimited-master/static/loader.gif' should write to 'static/loader.gif'
[copy-webpack-plugin] determined that 'D:/PROGRAMI/Github/medium-unlimited-master/static/loader.svg' should write to 'static/loader.svg'
[copy-webpack-plugin] determined that 'D:/PROGRAMI/Github/medium-unlimited-master/static/logo_128.png' should write to 'static/logo_128.png'
[copy-webpack-plugin] determined that 'D:/PROGRAMI/Github/medium-unlimited-master/static/logo_16.png' should write to 'static/logo_16.png'
[copy-webpack-plugin] determined that 'D:/PROGRAMI/Github/medium-unlimited-master/static/logo_48.png' should write to 'static/logo_48.png'
[copy-webpack-plugin] determined that 'D:/PROGRAMI/Github/medium-unlimited-master/static/logo.png' should write to 'static/logo.png'
[copy-webpack-plugin] reading D:\PROGRAMI\Github\medium-unlimited-master\static\floating_button_256.png to write to assets
[copy-webpack-plugin] reading D:\PROGRAMI\Github\medium-unlimited-master\static\loader.gif to write to assets
[copy-webpack-plugin] reading D:\PROGRAMI\Github\medium-unlimited-master\static\loader.svg to write to assets
[copy-webpack-plugin] reading D:\PROGRAMI\Github\medium-unlimited-master\static\logo_128.png to write to assets
[copy-webpack-plugin] reading D:\PROGRAMI\Github\medium-unlimited-master\static\logo_16.png to write to assets
[copy-webpack-plugin] reading D:\PROGRAMI\Github\medium-unlimited-master\static\logo_48.png to write to assets
[copy-webpack-plugin] reading D:\PROGRAMI\Github\medium-unlimited-master\static\logo.png to write to assets
[copy-webpack-plugin] writing 'manifest.json' to compilation assets from 'D:\PROGRAMI\Github\medium-unlimited-master\manifest.json'
[copy-webpack-plugin] writing 'static/floating_button_256.png' to compilation assets from 'D:\PROGRAMI\Github\medium-unlimited-master\static\floating_button_256.png'
[copy-webpack-plugin] writing 'static/logo_16.png' to compilation assets from 'D:\PROGRAMI\Github\medium-unlimited-master\static\logo_16.png'
[copy-webpack-plugin] writing 'static/logo_128.png' to compilation assets from 'D:\PROGRAMI\Github\medium-unlimited-master\static\logo_128.png'
[copy-webpack-plugin] writing 'static/loader.svg' to compilation assets from 'D:\PROGRAMI\Github\medium-unlimited-master\static\loader.svg'
[copy-webpack-plugin] writing 'static/logo_48.png' to compilation assets from 'D:\PROGRAMI\Github\medium-unlimited-master\static\logo_48.png'
[copy-webpack-plugin] writing 'static/logo.png' to compilation assets from 'D:\PROGRAMI\Github\medium-unlimited-master\static\logo.png'
[copy-webpack-plugin] writing 'static/loader.gif' to compilation assets from 'D:\PROGRAMI\Github\medium-unlimited-master\static\loader.gif'
i ｢webpack｣: Build Finished

webpack v4.16.5

9d42763b097a710210be
  size     name                    module                                    status
  489 B    global.js               (webpack)/buildin/global.js               built
  1.29 kB  analytics.js            ./src/analytics.js                        built
  8.36 kB  background.js           ./src/background.js                       built
  166 B    config.js               ./src/config.js                           built
  496 B    constants.js            ./src/constants.js                        built
  2.33 kB  cookie_interceptors.js  ./src/cookie_interceptors.js              built
  5.61 kB  medium-unlocker.js      ./src/medium-unlocker.js                  built
  735 B    storage.js              ./src/storage.js                          built
  1.43 kB  utils.js                ./src/utils.js                            built
  40 B     0                       multi babel-polyfill ./src/background.js  built

  size     name                    asset                                     status
  546 kB   background              background.bundle.js                      emitted
  851 kB   main                    main.bundle.js                            emitted
  1.5 kB   json                    manifest.json                             emitted
  6.47 kB  png                     static/floating_button_256.png            emitted
  392 B    png                     static/logo_16.png                        emitted
  2.56 kB  png                     static/logo_128.png                       emitted
  3.79 kB  svg                     static/loader.svg                         emitted
  965 B    png                     static/logo_48.png                        emitted
  51.7 kB  png                     static/logo.png                           emitted
  187 kB   gif                     static/loader.gif                         emitted

  Δt 4875ms (365 modules hidden)


[copy-webpack-plugin] unable to locate 'src/html' at 'D:\PROGRAMI\Github\medium-unlimited-master\src\html'
  0:0  error  webpack-stylish: <please report unknown message format>

× 1 problem (1 error, 0 warnings)

**Comment by emailsubjekt** [comment]
npm run build also finished with one error, but it didn't freeze this time

D:\PROGRAMI\Github\medium-unlimited-master>npm run build

> medium-unlimited@1.0.0 build D:\PROGRAMI\Github\medium-unlimited-master
> webpack --mode production

i ｢webpack｣: Starting Build
[copy-webpack-plugin] processing from: 'static' to: 'static'
[copy-webpack-plugin] processing from: 'src/html' to: 'html'
[copy-webpack-plugin] processing from: 'manifest.json' to: 'manifest.json'
[copy-webpack-plugin] begin globbing 'D:\PROGRAMI\Github\medium-unlimited-master\static/**/*' with a context of 'D:\PROGRAMI\Github\medium-unlimited-master\static'
[copy-webpack-plugin] WARNING - unable to locate 'src/html' at 'D:\PROGRAMI\Github\medium-unlimited-master\src\html'
[copy-webpack-plugin] begin globbing 'D:\PROGRAMI\Github\medium-unlimited-master\manifest.json' with a context of 'D:\PROGRAMI\Github\medium-unlimited-master'
[copy-webpack-plugin] determined that 'D:/PROGRAMI/Github/medium-unlimited-master/manifest.json' should write to 'manifest.json'
[copy-webpack-plugin] reading D:\PROGRAMI\Github\medium-unlimited-master\manifest.json to write to assets
[copy-webpack-plugin] determined that 'D:/PROGRAMI/Github/medium-unlimited-master/static/floating_button_256.png' should write to 'static/floating_button_256.png'
[copy-webpack-plugin] determined that 'D:/PROGRAMI/Github/medium-unlimited-master/static/loader.gif' should write to 'static/loader.gif'
[copy-webpack-plugin] determined that 'D:/PROGRAMI/Github/medium-unlimited-master/static/loader.svg' should write to 'static/loader.svg'
[copy-webpack-plugin] determined that 'D:/PROGRAMI/Github/medium-unlimited-master/static/logo_128.png' should write to 'static/logo_128.png'
[copy-webpack-plugin] determined that 'D:/PROGRAMI/Github/medium-unlimited-master/static/logo_16.png' should write to 'static/logo_16.png'
[copy-webpack-plugin] determined that 'D:/PROGRAMI/Github/medium-unlimited-master/static/logo_48.png' should write to 'static/logo_48.png'
[copy-webpack-plugin] determined that 'D:/PROGRAMI/Github/medium-unlimited-master/static/logo.png' should write to 'static/logo.png'
[copy-webpack-plugin] reading D:\PROGRAMI\Github\medium-unlimited-master\static\floating_button_256.png to write to assets
[copy-webpack-plugin] reading D:\PROGRAMI\Github\medium-unlimited-master\static\loader.gif to write to assets
[copy-webpack-plugin] reading D:\PROGRAMI\Github\medium-unlimited-master\static\loader.svg to write to assets
[copy-webpack-plugin] reading D:\PROGRAMI\Github\medium-unlimited-master\static\logo_128.png to write to assets
[copy-webpack-plugin] reading D:\PROGRAMI\Github\medium-unlimited-master\static\logo_16.png to write to assets
[copy-webpack-plugin] reading D:\PROGRAMI\Github\medium-unlimited-master\static\logo_48.png to write to assets
[copy-webpack-plugin] reading D:\PROGRAMI\Github\medium-unlimited-master\static\logo.png to write to assets
[copy-webpack-plugin] writing 'static/floating_button_256.png' to compilation assets from 'D:\PROGRAMI\Github\medium-unlimited-master\static\floating_button_256.png'
[copy-webpack-plugin] writing 'static/logo_16.png' to compilation assets from 'D:\PROGRAMI\Github\medium-unlimited-master\static\logo_16.png'
[copy-webpack-plugin] writing 'static/loader.svg' to compilation assets from 'D:\PROGRAMI\Github\medium-unlimited-master\static\loader.svg'
[copy-webpack-plugin] writing 'manifest.json' to compilation assets from 'D:\PROGRAMI\Github\medium-unlimited-master\manifest.json'
[copy-webpack-plugin] writing 'static/logo_48.png' to compilation assets from 'D:\PROGRAMI\Github\medium-unlimited-master\static\logo_48.png'
[copy-webpack-plugin] writing 'static/logo_128.png' to compilation assets from 'D:\PROGRAMI\Github\medium-unlimited-master\static\logo_128.png'
[copy-webpack-plugin] writing 'static/logo.png' to compilation assets from 'D:\PROGRAMI\Github\medium-unlimited-master\static\logo.png'
[copy-webpack-plugin] writing 'static/loader.gif' to compilation assets from 'D:\PROGRAMI\Github\medium-unlimited-master\static\loader.gif'
i ｢webpack｣: Build Finished

webpack v4.16.5

3be2f869611a6d0b0b32
  size     name        module                                    status
  496 B    29          ./src/constants.js                        built
  1.43 kB  47          ./src/utils.js                            built
  735 B    48          ./src/storage.js                          built
  1.29 kB  49          ./src/analytics.js                        built
  166 B    96          ./src/config.js                           built
  489 B    104         (webpack)/buildin/global.js               built
  40 B     146         multi babel-polyfill ./src/background.js  built
  8.36 kB  349         ./src/background.js                       built
  2.33 kB  350         ./src/cookie_interceptors.js              built
  5.61 kB  351         ./src/medium-unlocker.js                  built

  size     name        asset                                     status
  118 kB   background  background.bundle.js                      emitted
  154 kB   main        main.bundle.js                            emitted
  6.47 kB  png         static/floating_button_256.png            emitted
  392 B    png         static/logo_16.png                        emitted
  3.79 kB  svg         static/loader.svg                         emitted
  1.5 kB   json        manifest.json                             emitted
  965 B    png         static/logo_48.png                        emitted
  2.56 kB  png         static/logo_128.png                       emitted
  51.7 kB  png         static/logo.png                           emitted
  187 kB   gif         static/loader.gif                         emitted

  Δt 7475ms (358 modules hidden)


[copy-webpack-plugin] unable to locate 'src/html' at 'D:\PROGRAMI\Github\medium-unlimited-master\src\html'
  0:0  error  webpack-stylish: <please report unknown message format>

× 1 problem (1 error, 0 warnings)

D:\PROGRAMI\Github\medium-unlimited-master>

**Comment by emailsubjekt** [comment]
What should I do next? How do I apply this to Chrome?

**Comment by emailsubjekt** [comment]
It doesn't work. Chrome says there are errors, that's the error up there. I've tried going to medium, it says unlocking a huge lock come up, unlocks it but then all you can see are the ads that usually appear at the bottom. Am I doing something wrong?

**Comment by emailsubjekt** [comment]
Also, there was a website with the extension for download hosted on google cloud and it's gone now? Can you put it up again. This is a hassle and the extension works, I've tried it before.

**Comment by manojVivek** [comment]
@emailsubjekt  You can download and use the pre-built extension from https://medium-unlimited.ml/download/.

Please let me know if you face any issues.

**Comment by emailsubjekt** [comment]
The link works now, thanks! The extension works too! Thank you thank you thank you a hundred times!

**Comment by emailsubjekt** [comment]
For some reason it stopped working and chrome deactivated it.
