### ISSUE TITLE
Not working for medium.com links

### ISSUE THREAD

**Issue by impredicative** [manojVivek/medium-unlimited#17]
Sample failing link: https://medium.com/beyondminds/an-introduction-to-super-resolution-using-deep-learning-f60aff9a499d

Browser: FF 67

**Comment by manojVivek** [comment]
@impredicative Thanks for notifying me of this issue. I have identified the cause and fixed it in the version 1.4.5.

Please update your extension by visiting - https://addons.mozilla.org/en-US/firefox/addon/medium-unlimited-read-for-free/

Thank you!

**Comment by renblaze10** [comment]
@manojVivek it isn't working anymore. Tried the same link as mentioned by @impredicative
