### ISSUE TITLE
medium-unlimited-1.10.0 not work

### ISSUE THREAD

**Issue by dreamhomes** [manojVivek/medium-unlimited#183]
Chrome version: `95.0.4638.69`
Medium  unlimited version: `1.10.0`

Problem: This plugin work but unlimit content is not be showed.

Screenshot:
 
![image](https://user-images.githubusercontent.com/35626972/141717868-c76d7f00-11ea-4736-83e6-63f53871be57.png)

**Comment by huymichael** [comment]
any update :(

**Comment by Viibrant** [comment]
I'm also not able to view the content on Vivaldi on Ubuntu

**Comment by kascesar** [comment]
Same problem here. Any suggestion? 
Browser: Firefox 94 (64 bits)
OS: Kubuntu 20.04

**Comment by huymichael** [comment]
@manojVivek  could you please double check?

**Comment by megaduks** [comment]
I am getting `Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.` and the exception is raised in line 27 of `main.bundle.js`

**Comment by git-zjx** [comment]
Same problem here. 
Browser: Chrome 96.0.4664.93 (64 bits)
OS: Win11

**Comment by nprithviraj24** [comment]
Have you guys tried this [comment from #167](https://github.com/manojVivek/medium-unlimited/issues/167#issuecomment-884688708)? I cleared `medium`, and `towardsdatascience` cookies. It worked for me.

**Comment by dreamhomes** [comment]
We can get **another 3 free stories** by clearing medium and towardsdatascience cookies, but i think this is cache mechanism of medium to record page view. So this plugin is still not work...

**Comment by Ri8x** [comment]
Just the block the cookies instead no need for any thing else. Enjoy learning!

**Comment by aasutossh** [comment]
> 

you won't be logged in after blocking the cookies right?

**Comment by Ri8x** [comment]
> > 
> 
> you won't be logged in after blocking the cookies right?

yes, you wont be able to login in with cookies disabled

**Comment by und3fined** [comment]
I make Medium Unlocker it work with logged.

You can get it from https://github.com/und3fined/medium-unlocker

> > > 
> > 
> > 
> > you won't be logged in after blocking the cookies right?
> 
> yes, you wont be able to login in with cookies disabled
