### ISSUE TITLE
Chrome deactivates the extension? 

### ISSUE THREAD

**Issue by emailsubjekt** [manojVivek/medium-unlimited#21]
I installed everything but my extension gets blocked by chrome. At first it asks me 2 times should it deactivate it, I say no, then the third time a couple of minutes later it just notifies me that it blocked it?!

**Comment by Razgort** [comment]
Hello same here it seem off since 4 days

**Comment by manojVivek** [comment]
@emailsubjekt @Razgort @KamiGim Hi, Can you please try the updated instruction here - https://medium-unlimited.ml/download/ ? 

Please let me know if you face the problem again. Thanks!
