### ISSUE TITLE
Not working on levelup.gitconnected.com

### ISSUE THREAD

**Issue by gu18168** [manojVivek/medium-unlimited#22]
The extension doesn't work on the levelup.gitconnected.com like https://levelup.gitconnected.com/intro-to-web-programming-in-rust-for-nodejs-developers-1a9c048c4de1

**Comment by manojVivek** [comment]
@gu18168  It is enabled now, please update it to the latest version:
Firefox: https://addons.mozilla.org/en-US/firefox/addon/medium-unlimited-read-for-free/
Chrome: https://medium-unlimited.ml/download/
