### ISSUE TITLE
Not working on onezero.medium.com

### ISSUE THREAD

**Issue by ookangzheng** [manojVivek/medium-unlimited#23]

**Comment by manojVivek** [comment]
Hi @ookangzheng, Can I know which version of the extension and the browser are you using? 

It will be great if you could update it to the latest version(1.4.5) and try again.

**Comment by ookangzheng** [comment]
yap, its latest version on Firefox

**Comment by consal** [comment]
Yep, I noticed something changed yesterday, it stopped working. Firefox + plugin 1.4.5

**Comment by renblaze10** [comment]
Not sure what went wrong for you guys. It is working fine for me on the latest version of the extension and firefox.

**Comment by manojVivek** [comment]
@ookangzheng @consal @renblaze10 It is fixed now, please update it to the latest version:
Firefox: https://addons.mozilla.org/en-US/firefox/addon/medium-unlimited-read-for-free/
Chrome: https://medium-unlimited.ml/download/
