### ISSUE TITLE
Please add support for 

### ISSUE THREAD

**Issue by saikatm** [manojVivek/medium-unlimited#25]
add for support https://medium.com/@esther.louise/stop-trapping-yourself-with-to-do-lists-7cacf09277c6

thanks .

**Comment by manojVivek** [comment]
@saikatm   It is fixed now, please update it to the latest version:
Firefox: https://addons.mozilla.org/en-US/firefox/addon/medium-unlimited-read-for-free/
Chrome: https://medium-unlimited.ml/download/
