### ISSUE TITLE
Macbook pro 15 Chromium Edge not working

### ISSUE THREAD

**Issue by ookangzheng** [manojVivek/medium-unlimited#28]
<img width="1088" alt="圖片" src="https://user-images.githubusercontent.com/6301735/61169055-02d0a500-a547-11e9-875a-40e67b498637.png">

I have enabled Developer mode

**Comment by manojVivek** [comment]
@ookangzheng Hi, Can you please try the updated instruction here - https://medium-unlimited.ml/download/ ? 

Please let me know if you face the problem again. Thanks!
