### ISSUE TITLE
Adding new domains?

### ISSUE THREAD

**Issue by MostHated** [manojVivek/medium-unlimited#29]
Hey there,
    I was browsing through some articles and then I came to a locked on, looks like it is part of medium, just a different domain. https://itnext.io/ Is it possible to add URLS into the extension, or is it more complicated than that?

Thanks!
-MH

**Comment by manojVivek** [comment]
@MostHated @quanKM itnext.io is now added to the supported domains, please update it to the latest version:
Firefox: https://addons.mozilla.org/en-US/firefox/addon/medium-unlimited-read-for-free/
Chrome: https://medium-unlimited.ml/download/
