### ISSUE TITLE
This extension is not listed in the Chrome on Windows

### ISSUE THREAD

**Issue by jetaimefrc** [manojVivek/medium-unlimited#30]
![image](https://user-images.githubusercontent.com/24296018/61601417-6a7da300-ac5f-11e9-921e-66bc89b7b623.png)

I followed steps by steps. But it's not worked. 
In macOS => Okie, but in windows => Have been this issue
Hope you can fix this issue!

**Comment by jayrodge** [comment]
I'm also getting the same issue!

**Comment by Razgort** [comment]
Same here on my side

**Comment by ssahillppatell** [comment]
Dragging the .crx file directly into the extension menu will not help. You need to extract the .crx file as one extracts a .rar file by using either Winrar or 7zip. Then you need to click on "Load Extensions" tab in extension's menu and select the extracted folder as root directory.

**Comment by manojVivek** [comment]
@ssahillppatell Thanks for the workaround. 

@jetaimefrc @jayrodge @Razgort @faridvatani @Huong-nt I have updated the instruction and added a zip file for easier use. 

Can you please try again here - https://medium-unlimited.ml/download/ ?
