### ISSUE TITLE
Why so much permissions

### ISSUE THREAD

**Issue by vikaskyadav** [manojVivek/medium-unlimited#38]
I don't understand the purpose behind of getting permissions to access data for *www.google.com* . Can anybody explain?

**Comment by ttuygun** [comment]
https://github.com/manojVivek/medium-unlimited/blob/master/src/background.js#L64

**Comment by vikaskyadav** [comment]
Hi, I can understand the `function` but I am unable to understand the `purpose` or `necessity` for this.

**Comment by MightyPork** [comment]
this made me not install the plugin. I *guess* that the URL is corrupted by medium after the membership prompt appears and it uses google search to recover the original, but some clarity would help

**Comment by manojVivek** [comment]
@vikaskyadav @ttuygun @MightyPork Hey guys, thanks for raising this concern. 

The permission for `google.com` was required for the previous way of unlocking when some articles would need a google search to know the original content URL. 

But now we have moved on the `twitter referral URL` based unlocking so this permission is no longer needed. I have removed it with version `1.4.11`. 

I would be happy to discuss if you still have any questions.

**Comment by MightyPork** [comment]
I believe you, but this firefox install pop up is still problematic - people install it to evade medium paywall. There's no way to see what's the "other 15 sites", besides looking in the repository and trusting that the published version is really built from that. (ftr, of the listed domains, i have heard only of medium.com and hackernoon)

![Screenshot_20191027_140238](https://user-images.githubusercontent.com/2041118/67635018-8928b100-f8c2-11e9-8295-0e55fb16bf86.png)

**Comment by samomar** [comment]
> trusting that the published version is really built from that

the sites are in the manifest and you can build your own version
