### ISSUE TITLE
Not Working now

### ISSUE THREAD

**Issue by jayrodge** [manojVivek/medium-unlimited#4]
I tried this extension, this doesn't now I guess due to the changes medium made.

**Comment by manojVivek** [comment]
@jayrodge Can you please attach the link to the article that is not working for you?

**Comment by jayrodge** [comment]
[https://medium.com/inc./lebron-james-just-gave-business-leaders-a-quick-brutal-lesson-in-management-b86623d13744](url)
[https://medium.com/inc./why-i-wake-up-at-4-a-m-every-day-c99321b00236](url)

**Comment by manojVivek** [comment]
@jayrodge There are a few publications like `inc.` for which the extension will not work as they don't even allow content for fresh non-logged in sessions.

The extension works based on this article - https://medium.com/@Evanthel/how-to-read-premium-medium-articles-for-free-437ca253ce64
