### ISSUE TITLE
Issue installing addon in Firefox from source

### ISSUE THREAD

**Issue by joao-neves95** [manojVivek/medium-unlimited#41]
I am having issues building the project from source and install it on Firefox.
No issues with Chrome though.

**What do I have to do in order to install "medium-unlimited" from source in Firefox?**

Windows 10
Firefox v70.0
Error message: "This add-on could not be installed because it appears to be corrupt".

Steps to reproduce:
1 - git clone
2 - npm i
3- npm run build
4 - zip "dist/"
5 - install in firefox (error)

**Comment by joao-neves95** [comment]
@manojVivek

**Comment by manojVivek** [comment]
@joao-neves95 I just found that firefox requires a couple of changes for this to work.

1. You need to add set an addon ID in the manifest.json with the `browser_specific_settings`. Check - https://extensionworkshop.com/documentation/develop/extensions-and-the-add-on-id/#basic-workflow-with-no-add-on-id
2. Need to zip the only the files inside the `dist/*` and not the `dist` folder itself. You shouldn't include the parent folder in the zip, the root of the zip should include the `manifest.json` file. 

Please try these and let me know. Thanks!

**Comment by joao-neves95** [comment]
Hello and thank you for the response.

I've decided to create an .xpi package on Firefox's Add-on Developer Hub with the "On your own" option of the "How to Distribute this Version" section of the "Submit a New Add-on" page.
It was a fast solution.

Best regards!
