### ISSUE TITLE
Custom medium domain

### ISSUE THREAD

**Issue by binhle12** [manojVivek/medium-unlimited#42]
Hi @manojVivek ,
I'm using this extension on Firefox. It's very good. 🍺🍺🍺
But there is a custom medium domain: engineering.opsgenie.com that is not listed in [your list](https://addons.mozilla.org/vi/firefox/addon/medium-unlimited-read-for-free/).
Please take a look.
Thanks

**Comment by manojVivek** [comment]
Hi, I have added support for this domain in version 1.4.14.
