### ISSUE TITLE
Please add https://calia.me/

### ISSUE THREAD

**Issue by gioxx** [manojVivek/medium-unlimited#43]
Can I ask You to add https://calia.me/ to the unlock list?
Thanks a lot.

**Comment by trK54Ylmz** [comment]
I've managed to add custom domain such as `https://instagram-engineering.com/`

I've added the domain you've mentioned @gioxx 

[medium-unlimited-1.4.11-custom.zip](https://github.com/manojVivek/medium-unlimited/files/3907459/medium-unlimited-1.4.11-custom.zip)

cc @manojVivek

**Comment by manojVivek** [comment]
@trK54Ylmz Thanks!
@gioxx I have released a new version 1.4.13 that supports calia.me and instagram-engineering.com.

Please update from here:
Firefox: https://addons.mozilla.org/en-US/firefox/addon/medium-unlimited-read-for-free/
Chrome: https://medium-unlimited.ml/download/
