### ISSUE TITLE
How to manually install the extension on firefox

### ISSUE THREAD

**Issue by mmphego** [manojVivek/medium-unlimited#45]
It seems like firefox has taken down the extension from the addon website. How can one install the extension manually?

Thanks for the great work.

**Comment by maacpiash** [comment]
I am assuming you have Node.js and Git installed on your machine.

First, build this package:

- Clone this repo
- Run `npm i`
- Run `npm run build`

The build is now in the `./dist` folder, with a `manifest.json` file.

Now, on FireFox:

- Go to `about:debugging`
- Click "This FireFox"
- Click "Load Temporary Add-on..."
- Select the `manifest.json` file produced by building

I'm afraid this is a temporary solution. For permanently adding this to FF, beta or nightly version of FF might be required.
