### ISSUE TITLE
[Bug] I dont think the extension works correctly

### ISSUE THREAD

**Issue by ItsRauf** [manojVivek/medium-unlimited#46]
As seen in the image, it does not let me read the rest of the article

![image](https://user-images.githubusercontent.com/31735267/69595542-da18eb80-0fcd-11ea-8194-94ddff8f2b85.png)

**Comment by ItsRauf** [comment]
it has the same result when signed in too
![image](https://user-images.githubusercontent.com/31735267/69595835-a68a9100-0fce-11ea-80e4-537ac093fedd.png)

**Comment by manojVivek** [comment]
Is it just this article or every article? 
It works perfect for me, Can you please try removing the extensions and re-installing it?

**Comment by CuongStf** [comment]
same prob for me

**Comment by manojVivek** [comment]
Closing due to lack of information.

**Comment by cuongdevjs** [comment]
sometimes some news still locked although i was uninstalled and reinstall
