### ISSUE TITLE
Site unsupported

### ISSUE THREAD

**Issue by vstyler96** [manojVivek/medium-unlimited#54]
I have noticed there's an unsupported website: https://blog.devartis.com/*

I tried to add the site, but I failed so hard.

Thanks for your help.

Best Regards.

**Comment by johnumus** [comment]
Hey, you can go to my branch and build it with `npm install` then `npm run build`. Or wait for the PR to be merged.

**Comment by manojVivek** [comment]
@vstyler96   I have released a new version with this change.

Thanks to @johnumus.

Please update it from here:
Firefox: https://addons.mozilla.org/en-US/firefox/addon/medium-unlimited-read-for-free/
Chrome: https://manojvivek.github.io/medium-unlimited/download/
