### ISSUE TITLE
Blog HipoLabs

### ISSUE THREAD

**Issue by Kuroiteiken** [manojVivek/medium-unlimited#58]
Hello, could you add https://blog.hipolabs.com/ to sitelist too??

**Comment by johnumus** [comment]
Sure I'll add it in around 6-8 hours next. 

Maybe I'll add a guide to how to add site into the project. 

But you have still wait for it to be merged or build it from the the branch that is added new site.

**Comment by faisalzone** [comment]
https://ux.shopify.com/designing-address-forms-for-everyone-everywhere-f481f6baf513?source=grid_home---------0-59-----------------18---7e2b45a2_e169_4367_bdc7_288811fb9b43--2 This site as well if you can :) :)

**Comment by manojVivek** [comment]
@Kuroiteiken @faisalzone A new version supporting these domains will go live today.
