### ISSUE TITLE
Please support for android.jlelse.eu

### ISSUE THREAD

**Issue by hienlt0610** [manojVivek/medium-unlimited#59]
Hi, could you add https://android.jlelse.eu to supported list file?

**Comment by paulrenfik** [comment]
> Hi, could you add https://android.jlelse.eu to supported list file?

just edit manifest.json

**Comment by ilhamazdi** [comment]
Current release is partially working. It won't work on some newer articles like this https://android.jlelse.eu/handling-files-in-code-after-the-android-10-released-2bea0e16d35. It's just endlessly refreshes the page.

**Comment by manojVivek** [comment]
@hienlt0610 @paulrenfik A new version supporting https://android.jlelse.eu will go live today.
