### ISSUE TITLE
Failed to unlock article using new chromium-based Microsoft Edge

### ISSUE THREAD

**Issue by ajebulon** [manojVivek/medium-unlimited#63]
**Browser version:**
Microsoft Edge
Version 80.0.361.69 (Official build) (64-bit)

**Description:**
Title is pretty self explanatory. This extension tried to unlock the article but it kept failing.

**Comment by cumanzor** [comment]
Edge (80.0.361.109) Mac OS, extension is working fine here.

**Comment by ajebulon** [comment]
Tried again with Version 81.0.416.53 (Official build) (64-bit), same things happened. However this issue was resolved by logging in to the Medium account.
