### ISSUE TITLE
Updated Chrome version - Cannot load background script

### ISSUE THREAD

**Issue by lakshyapriyadarshi** [manojVivek/medium-unlimited#67]
![Screenshot from 2020-04-29 11-56-50](https://user-images.githubusercontent.com/37311397/80566626-091a0a00-8a11-11ea-9536-f034c010b01d.png)

**Comment by manojVivek** [comment]
@lakshyapriyadarshi It looks like downloaded the source code from github instead of the built bundle.

Can you follow the instructions from this page - https://manojvivek.github.io/medium-unlimited/download/

It has a link to download the built extension.

**Comment by lakshyapriyadarshi** [comment]
Thanks, @manojVivek ! This was indeed the problem and is now resolved.
