### ISSUE TITLE
Adding domain: https://blog.kotlin-academy.com/ did not work

### ISSUE THREAD

**Issue by ShivamDev31** [manojVivek/medium-unlimited#69]
I tried to add `https://blog.kotlin-academy.com/` in `manifest.json` and `background.bundle.js` and it did not work. Moreover, I'm seeing this error now. 

<img width="398" alt="Screenshot 2020-05-04 at 1 50 46 PM" src="https://user-images.githubusercontent.com/4529848/80949071-ec1a7800-8e10-11ea-95f0-c7ebc2a15595.png">

<img width="672" alt="Screenshot 2020-05-04 at 2 10 04 PM" src="https://user-images.githubusercontent.com/4529848/80949102-f9376700-8e10-11ea-8def-9b44d6d1e5ae.png">

Can you add in the README.md proper procedure to add a domain manually until you add an interface.

**Comment by M7meDMost** [comment]
#70

**Comment by ShivamDev31** [comment]
@M7meDMost helped me with it. I was missing adding the domain to the 2nd list in manifest filed. Added in 2nd list and it worked.
