### ISSUE TITLE
i used your extension it's very good but below website is not working.

### ISSUE THREAD

**Issue by NikulGoyani369** [manojVivek/medium-unlimited#73]
https://writingcooperative.com/4-things-i-did-to-improve-my-vocabulary-37c173365da6

**Comment by cnscorpions** [comment]
@NikulGoyani369 you could ask @manojVivek to add this domain to urlsList and publish a new release

**Comment by anwarDigitalDividend** [comment]
also need help with domain as well https://blog.echobind.com/  @manojVivek

**Comment by manojVivek** [comment]
@NikulGoyani369 @cnscorpions @anwarDigitalDividend Domains supported in the latest version, v1.6.0.

Link to update: https://manojvivek.github.io/medium-unlimited/download/

**Comment by NikulGoyani369** [comment]
@manojVivek Thank you. it very helpful. 
did you update all URL or other domains?
