### ISSUE TITLE
Not working in unbounded.io

### ISSUE THREAD

**Issue by azizbekian** [manojVivek/medium-unlimited#74]
Plugin doesn't work on specific pages, e.g. 

https://unbounded.io/securing-api-gateway-with-okta-serverless-framework-and-ssm-9e679af614e2

<img width="704" alt="Screen Shot 2020-05-23 at 10 20 54 PM" src="https://user-images.githubusercontent.com/3052023/82737665-bb5c9d00-9d43-11ea-9162-4be5b5ececb1.png">

**Comment by ameenpv** [comment]
Here are the custom domains supported by this extension and it doesn't contain unbounded.io!

- https://towardsdatascience.com
- https://hackernoon.com
- https://medium.freecodecamp.org
- https://psiloveyou.xyz
- https://betterhumans.coach.me
- https://codeburst.io
- https://theascent.pub
- https://medium.mybridge.co
- https://uxdesign.cc
- https://levelup.gitconnected.com
- https://itnext.io
- https://entrepreneurshandbook.co
- https://proandroiddev.com
- https://blog.prototypr.io
- https://thebolditalic.com
- https://blog.usejournal.com
- https://blog.angularindepth.com
- https://uxplanet.org
- https://instagram-engineering.com
- https://calia.me
- https://productcoalition.com
- https://engineering.opsgenie.com
- https://android.jlelse.eu
- https://blog.bitsrc.io
- https://blog.devartis.com
- https://blog.maddevs.io
- https://blog.getambassador.io
- https://uxplanet.org
- https://instagram-engineering.com
- https://calia.me
- https://productcoalition.com
- https://engineering.opsgenie.com
- https://android.jlelse.eu
- https://robinhood.engineering
- https://blog.hipolabs.com
- https://ux.shopify.com

**Comment by manojVivek** [comment]
Domain supported in the latest version, v1.6.0. 

Link to update: https://manojvivek.github.io/medium-unlimited/download/
