### ISSUE TITLE
Taken off of Chrome webstore

### ISSUE THREAD

**Issue by IshanArya** [manojVivek/medium-unlimited#8]
Hi. The extension cannot be found on the Chrome webstore (except for [this one](https://chrome.google.com/webstore/detail/mediumcom-unlimited-readi/keckgflodjmhejpbhfbfoioonoeeckng?utm_source=chrome-ntp-icon) that seems like malware). Are there plans to put put the extension back on the store, or should we just manually install it from now on?

Thanks.

**Comment by manojVivek** [comment]
Hi @IshanArya, The extension is removed from the chrome store as it is violating the store policy.

Here is how you can get it now - https://medium-unlimited.ml/download/

Hope this helps, let me know if you have any questions.

**Comment by IshanArya** [comment]
Alright thank you!

**Comment by doggy8088** [comment]
@manojVivek Why [this one](https://chrome.google.com/webstore/detail/mediumcom-unlimited-readi/keckgflodjmhejpbhfbfoioonoeeckng?utm_source=chrome-ntp-icon) is violating the store policy?

**Comment by manojVivek** [comment]
It is not reported in yet! 😄

**Comment by doggy8088** [comment]
@manojVivek You might try publish again. Choose another name, something like **Medium.com Reader: Improved**. 😆
