### ISSUE TITLE
an error in building: `unable to locate...`

### ISSUE THREAD

**Issue by beigirad** [manojVivek/medium-unlimited#9]
at the end of `npm install` command, when I ran your snippet code for build this extension:
```
npm run dev         #For local development
#or
npm run build       #For production release
```

I received this error:
```
[copy-webpack-plugin] unable to locate 'src/html' at '/Users/farhad/Desktop/medium-unlimited-master/src/html'
  0:0  error  webpack-stylish: <please report unknown message format>

✖ 1 problem (1 error, 0 warnings)
```
Could you make a guide for non-web developers?

Your extension was removed from chrome store.

**Comment by manojVivek** [comment]
@beigirad You can use a pre-built bundle following the instructions in this link - https://medium-unlimited.ml/download/

Let me know if that was not helpful.

**Comment by beigirad** [comment]
now I using that bundle, but I want to make it myself for curiosity.
If it's not possible, you can close this issue.

**Comment by manojVivek** [comment]
@beigirad  Are you running the command from the root of the repo? 

In your case, you should be in the `/Users/farhad/Desktop/medium-unlimited-master` path when you run the build command.
