### ISSUE TITLE
Missing domain: blog.kubernauts.io

### ISSUE THREAD

**Issue by ad-m** [manojVivek/medium-unlimited#95]
Example post: https://blog.kubernauts.io/k3s-with-metallb-on-multipass-vms-ac2b37298589

**Comment by ssi-anik** [comment]
domain [https://blog.securityevaluators.com/](https://blog.securityevaluators.com/) is missing as well

**Comment by manojVivek** [comment]
Domain supported in the latest version(v1.6.0).
