### ISSUE TITLE
1.4.17 doesn't login at all

### ISSUE THREAD

**Issue by Drjacky** [manojVivek/medium-unlimited#98]
I have 1.4.9 for a while and since a few days ago, the issue has been started; Forget logged in user.
Then, I've upgraded to 1.4.17 and it doesn't login at all.

**Comment by EugeneGohh** [comment]
Ver 1.4.17 is not the latest version. The latest version is Ver 1.6.0.

**Comment by Drjacky** [comment]
The problem is fixed on 1.6.0.
